version: '3.8'

services:
  mysql:
    image: mysql:9.0
    container_name: mysql9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 53cret
      MYSQL_DATABASE: spring_crud
      MYSQL_USER: yu71
      MYSQL_PASSWORD: 53cret
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data: