spring:
  application.name: spring-boot-thymeleaf-sample2
  datasource:
    url: jdbc:mysql://localhost:3308/spring_crud
    username: yu71
    password: 53cret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect